// Données des projets (à remplacer par des appels BDD plus tard)
export const projects = [
  {
    id: 1,
    name: "Projet Alpha",
    progress: 85,
    description:
      "Développement d'une application web moderne avec React et Node.js",
    longDescription:
      "Ce projet ambitieux vise à créer une plateforme web complète utilisant les technologies les plus récentes. L'application permettra aux utilisateurs de gérer leurs projets, collaborer en temps réel et suivre leurs objectifs avec des outils avancés d'analytics et de reporting.",
    details: {
      startDate: "15 Janvier 2024",
      endDate: "30 Mars 2024",
      team: "5 développeurs",
    },
    deadline: {
      kickOff: "20 Janvier 2024",
      followUp: "15 Février 2024",
      keynote: "25 Mars 2024",
      daysRemaining: 12,
    },
    documentation: {
      pdfUrl: "/docs/projet-alpha.pdf",
      pdfName: "Spécifications Alpha",
    },
    tasks: [
      "Interface utilisateur terminée",
      "API backend en cours",
      "Tests unitaires à faire",
      "Documentation à compléter",
    ],
    team: [
      { name: "Marie Dubois", role: "Lead Developer", avatar: "👩‍💻" },
      { name: "Thomas Martin", role: "Frontend Developer", avatar: "👨‍💻" },
      { name: "Sophie Bernard", role: "Backend Developer", avatar: "👩‍💻" },
      { name: "Lucas Petit", role: "UI/UX Designer", avatar: "👨‍🎨" },
      { name: "Emma Roux", role: "QA Engineer", avatar: "👩‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: false, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: false, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
    resources: {
      bootstrap: [
        { name: "Guide de démarrage", action: "Voir", url: "/docs/bootstrap/guide-demarrage.pdf" },
      ],
      kickOff: [
        { name: "Présentation projet", action: "Voir", url: "/docs/kickoff/presentation.pdf" },
        { name: "Planning", action: "Télécharger", url: "/docs/kickoff/planning.xlsx" },
        { name: "Équipe", action: "Voir", url: "/docs/kickoff/equipe.pdf" }
      ],
      projet: [
        { name: "API Documentation", action: "Voir", url: "/docs/api-docs.pdf" },
        { name: "Guide utilisateur", action: "Télécharger", url: "/docs/guide-utilisateur.pdf" }
      ]
    },
    teams: [
      { id: 1, name: 'MAR_5', members: [{ name: 'William LACROIX', avatar: '👤' }], maxMembers: 3 },
      { id: 2, name: 'MAR_1', members: [{ name: 'Paul LOUIS', avatar: '👤' }], maxMembers: 3 },
      { id: 3, name: 'MAR_10', members: [{ name: 'Philippe LEFEVRE', avatar: '👤' }], maxMembers: 3 },
    ],
  },
  {
    id: 2,
    name: "Projet Beta",
    progress: 45,
    description:
      "Création d'une interface utilisateur intuitive et responsive",
    longDescription:
      "Ce projet se concentre sur la création d'une interface utilisateur moderne et intuitive qui s'adapte parfaitement à tous les appareils. L'objectif est de fournir une expérience utilisateur exceptionnelle avec des animations fluides et une navigation intuitive.",
    details: {
      startDate: "20 Janvier 2024",
      endDate: "15 Avril 2024",
      team: "3 développeurs",
    },
    deadline: {
      kickOff: "25 Janvier 2024",
      followUp: "20 Février 2024",
      keynote: "10 Avril 2024",
      daysRemaining: 35,
    },
    documentation: {
      pdfUrl: "/docs/projet-beta.pdf",
      pdfName: "Maquettes Beta",
    },
    tasks: [
      "Design system créé",
      "Composants UI en cours",
      "Tests d'accessibilité",
      "Optimisation mobile",
    ],
    team: [
      { name: "Alexandre Moreau", role: "UI/UX Designer", avatar: "👨‍🎨" },
      { name: "Julie Leroy", role: "Frontend Developer", avatar: "👩‍💻" },
      { name: "Pierre Durand", role: "Accessibility Expert", avatar: "👨‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Responsive Design", description: "Adaptation de l'UI à tous les formats d'écran." }
    ],
    skills: ["Figma", "React", "Accessibility", "CSS"],
    resources: {
      bootstrap: [
        { name: "Guide de démarrage", action: "Voir", url: "/docs/bootstrap/guide-demarrage.pdf" },
        { name: "Architecture", action: "Voir", url: "/docs/bootstrap/architecture.pdf" },
        { name: "Configuration", action: "Télécharger", url: "/docs/bootstrap/config.zip" }
      ],
      kickOff: [
        { name: "Présentation projet", action: "Voir", url: "/docs/kickoff/presentation.pdf" },
        { name: "Planning", action: "Télécharger", url: "/docs/kickoff/planning.xlsx" },
        { name: "Équipe", action: "Voir", url: "/docs/kickoff/equipe.pdf" }
      ],
      projet: [
        { name: "Maquettes Beta", action: "Voir", url: "/docs/projet-beta.pdf" },
        { name: "API Documentation", action: "Voir", url: "/docs/api-docs.pdf" },
        { name: "Guide utilisateur", action: "Télécharger", url: "/docs/guide-utilisateur.pdf" }
      ]
    },
    teams: [
      { id: 1, name: 'BETA_1', members: [{ name: 'Alexandre Moreau', avatar: '👨‍🎨' }], maxMembers: 3 },
      { id: 2, name: 'BETA_2', members: [{ name: 'Julie Leroy', avatar: '👩‍💻' }], maxMembers: 3 },
      { id: 3, name: 'BETA_3', members: [], maxMembers: 3 },
    ],
  },
  {
    id: 3,
    name: "Projet Gamma",
    progress: 92,
    description:
      "Implémentation de fonctionnalités avancées et optimisation des performances",
    longDescription:
      "Ce projet vise à optimiser les performances d'une application existante et à ajouter des fonctionnalités avancées. L'objectif est d'améliorer significativement la vitesse de chargement et l'expérience utilisateur globale.",
    details: {
      startDate: "10 Janvier 2024",
      endDate: "25 Février 2024",
      team: "4 développeurs",
    },
    deadline: {
      kickOff: "15 Janvier 2024",
      followUp: "10 Février 2024",
      keynote: "20 Février 2024",
      daysRemaining: 3,
    },
    documentation: {
      pdfUrl: "/docs/projet-gamma.pdf",
      pdfName: "Architecture Gamma",
    },
    tasks: [
      "Optimisation terminée",
      "Tests de charge réussis",
      "Documentation technique",
      "Déploiement en production",
    ],
    team: [
      { name: "Camille Rousseau", role: "Performance Engineer", avatar: "👩‍💻" },
      { name: "Antoine Lefevre", role: "Backend Developer", avatar: "👨‍💻" },
      { name: "Sarah Dubois", role: "DevOps Engineer", avatar: "👩‍💻" },
      { name: "Maxime Bernard", role: "QA Engineer", avatar: "👨‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 4,
    name: "Projet Delta",
    progress: 23,
    description:
      "Intégration d'APIs externes et développement de microservices",
    longDescription:
      "Ce projet consiste à créer une architecture microservices robuste et à intégrer plusieurs APIs externes. L'objectif est de construire un système scalable et maintenable.",
    details: {
      startDate: "25 Janvier 2024",
      endDate: "30 Mai 2024",
      team: "6 développeurs",
    },
    deadline: {
      kickOff: "30 Janvier 2024",
      followUp: "25 Février 2024",
      keynote: "25 Mai 2024",
      daysRemaining: 78,
    },
    documentation: {
      pdfUrl: "/docs/projet-delta.pdf",
      pdfName: "APIs Delta",
    },
    tasks: [
      "Architecture définie",
      "Premier microservice",
      "Documentation API",
      "Tests d'intégration",
    ],
    team: [
      { name: "Nicolas Martin", role: "Architect", avatar: "👨‍💻" },
      { name: "Claire Simon", role: "Backend Developer", avatar: "👩‍💻" },
      { name: "David Garcia", role: "API Developer", avatar: "👨‍💻" },
      { name: "Laura Moreau", role: "DevOps Engineer", avatar: "👩‍💻" },
      { name: "Thomas Leroy", role: "Integration Specialist", avatar: "👨‍💻" },
      { name: "Emma Dubois", role: "QA Engineer", avatar: "👩‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 5,
    name: "Projet Epsilon",
    progress: 67,
    description: "Mise en place d'une architecture cloud-native et sécurisée",
    longDescription:
      "Ce projet vise à migrer l'infrastructure existante vers une architecture cloud-native avec un focus particulier sur la sécurité. L'objectif est d'améliorer la scalabilité et la résilience du système.",
    details: {
      startDate: "5 Février 2024",
      endDate: "20 Juin 2024",
      team: "7 développeurs",
    },
    deadline: {
      kickOff: "10 Février 2024",
      followUp: "5 Mars 2024",
      keynote: "15 Juin 2024",
      daysRemaining: 95,
    },
    documentation: {
      pdfUrl: "/docs/projet-epsilon.pdf",
      pdfName: "Architecture Cloud",
    },
    tasks: [
      "Infrastructure cloud",
      "Sécurité implémentée",
      "Monitoring en cours",
      "Tests de sécurité",
    ],
    team: [
      { name: "Sophie Martin", role: "Cloud Architect", avatar: "👩‍💻" },
      { name: "Lucas Bernard", role: "Security Engineer", avatar: "👨‍💻" },
      { name: "Julie Rousseau", role: "DevOps Engineer", avatar: "👩‍💻" },
      { name: "Pierre Dubois", role: "Infrastructure Engineer", avatar: "👨‍💻" },
      { name: "Camille Leroy", role: "Security Specialist", avatar: "👩‍💻" },
      { name: "Antoine Moreau", role: "Monitoring Engineer", avatar: "👨‍💻" },
      { name: "Sarah Garcia", role: "QA Engineer", avatar: "👩‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 6,
    name: "Projet Zeta",
    progress: 78,
    description: "Développement d'algorithmes de machine learning et d'IA",
    longDescription:
      "Ce projet se concentre sur le développement d'algorithmes de machine learning avancés pour l'analyse prédictive et l'automatisation intelligente. L'objectif est de créer des modèles performants et éthiques.",
    details: {
      startDate: "15 Février 2024",
      endDate: "10 Juillet 2024",
      team: "4 développeurs",
    },
    deadline: {
      kickOff: "20 Février 2024",
      followUp: "15 Mars 2024",
      keynote: "5 Juillet 2024",
      daysRemaining: 125,
    },
    documentation: {
      pdfUrl: "/docs/projet-zeta.pdf",
      pdfName: "Algorithms ML",
    },
    tasks: [
      "Modèles entraînés",
      "API ML créée",
      "Tests de précision",
      "Optimisation en cours",
    ],
    team: [
      { name: "Marie Dubois", role: "ML Engineer", avatar: "👩‍💻" },
      { name: "Thomas Martin", role: "Data Scientist", avatar: "👨‍💻" },
      { name: "Sophie Bernard", role: "AI Researcher", avatar: "👩‍💻" },
      { name: "Lucas Petit", role: "Backend Developer", avatar: "👨‍💻" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 7,
    name: "Projet Eta",
    progress: 34,
    description:
      "Création d'une plateforme de gestion de données en temps réel",
    longDescription:
      "Ce projet vise à créer une plateforme capable de traiter et analyser des données en temps réel. L'objectif est de fournir des insights instantanés pour la prise de décision.",
    details: {
      startDate: "1 Mars 2024",
      endDate: "15 Août 2024",
      team: "5 développeurs",
    },
    deadline: {
      kickOff: "5 Mars 2024",
      followUp: "1 Avril 2024",
      keynote: "10 Août 2024",
      daysRemaining: 140,
    },
    documentation: {
      pdfUrl: "/docs/projet-eta.pdf",
      pdfName: "Platform Realtime",
    },
    tasks: [
      "Base de données conçue",
      "API temps réel",
      "Interface admin",
      "Tests de performance",
    ],
    team: [
      { name: "Emma Roux", role: "Data Engineer", avatar: "👩‍💻" },
      { name: "Maxime Bernard", role: "Backend Developer", avatar: "👨‍💻" },
      { name: "Laura Moreau", role: "Frontend Developer", avatar: "👩‍💻" },
      { name: "Nicolas Simon", role: "DevOps Engineer", avatar: "👨‍💻" },
      { name: "Claire Dubois", role: "QA Engineer", avatar: "👩‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 8,
    name: "Projet Theta",
    progress: 56,
    description:
      "Optimisation de processus métier et automatisation des tâches",
    longDescription:
      "Ce projet se concentre sur l'analyse et l'optimisation des processus métier existants, avec l'objectif d'automatiser les tâches répétitives et d'améliorer l'efficacité opérationnelle.",
    details: {
      startDate: "10 Mars 2024",
      endDate: "30 Septembre 2024",
      team: "3 développeurs",
    },
    deadline: {
      kickOff: "15 Mars 2024",
      followUp: "10 Avril 2024",
      keynote: "25 Septembre 2024",
      daysRemaining: 165,
    },
    documentation: {
      pdfUrl: "/docs/projet-theta.pdf",
      pdfName: "Processus BPM",
    },
    tasks: [
      "Analyse des processus",
      "Automatisation en cours",
      "Formation utilisateurs",
      "Tests d'acceptation",
    ],
    team: [
      { name: "Pierre Durand", role: "Business Analyst", avatar: "👨‍💻" },
      { name: "Julie Leroy", role: "Process Engineer", avatar: "👩‍💻" },
      { name: "Alexandre Moreau", role: "Automation Developer", avatar: "👨‍💻" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 9,
    name: "Projet Iota",
    progress: 89,
    description: "Développement d'une solution mobile cross-platform",
    longDescription:
      "Ce projet vise à créer une application mobile qui fonctionne sur iOS et Android avec une base de code partagée. L'objectif est de fournir une expérience utilisateur cohérente sur toutes les plateformes.",
    details: {
      startDate: "20 Février 2024",
      endDate: "25 Mai 2024",
      team: "4 développeurs",
    },
    deadline: {
      kickOff: "25 Février 2024",
      followUp: "20 Mars 2024",
      keynote: "20 Mai 2024",
      daysRemaining: 45,
    },
    documentation: {
      pdfUrl: "/docs/projet-iota.pdf",
      pdfName: "Mobile App",
    },
    tasks: [
      "App iOS terminée",
      "App Android en cours",
      "Tests sur appareils",
      "Publication stores",
    ],
    team: [
      { name: "Camille Rousseau", role: "Mobile Developer", avatar: "👩‍💻" },
      { name: "Antoine Lefevre", role: "iOS Developer", avatar: "👨‍💻" },
      { name: "Sarah Dubois", role: "Android Developer", avatar: "👩‍💻" },
      { name: "Maxime Bernard", role: "QA Engineer", avatar: "👨‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 10,
    name: "Projet Kappa",
    progress: 12,
    description: "Intégration de systèmes de paiement et de sécurité",
    longDescription:
      "Ce projet se concentre sur l'intégration sécurisée de systèmes de paiement et la mise en place de mesures de sécurité robustes pour protéger les données sensibles des utilisateurs.",
    details: {
      startDate: "1 Avril 2024",
      endDate: "30 Octobre 2024",
      team: "6 développeurs",
    },
    deadline: {
      kickOff: "5 Avril 2024",
      followUp: "1 Mai 2024",
      keynote: "25 Octobre 2024",
      daysRemaining: 185,
    },
    documentation: {
      pdfUrl: "/docs/projet-kappa.pdf",
      pdfName: "Sécurité Paiement",
    },
    tasks: [
      "Analyse sécurité",
      "Intégration Stripe",
      "Tests de sécurité",
      "Certification PCI",
    ],
    team: [
      { name: "Nicolas Martin", role: "Security Engineer", avatar: "👨‍💻" },
      { name: "Claire Simon", role: "Payment Specialist", avatar: "👩‍💻" },
      { name: "David Garcia", role: "Backend Developer", avatar: "👨‍💻" },
      { name: "Laura Moreau", role: "Compliance Officer", avatar: "👩‍💻" },
      { name: "Thomas Leroy", role: "QA Engineer", avatar: "👨‍🔬" },
      { name: "Emma Dubois", role: "Security Analyst", avatar: "👩‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 11,
    name: "Projet Lambda",
    progress: 73,
    description:
      "Création d'un dashboard analytique avec visualisations avancées",
    longDescription:
      "Ce projet vise à créer un dashboard analytique complet avec des visualisations de données avancées pour aider à la prise de décision basée sur les données.",
    details: {
      startDate: "15 Mars 2024",
      endDate: "20 Juillet 2024",
      team: "4 développeurs",
    },
    deadline: {
      kickOff: "20 Mars 2024",
      followUp: "15 Avril 2024",
      keynote: "15 Juillet 2024",
      daysRemaining: 110,
    },
    documentation: {
      pdfUrl: "/docs/projet-lambda.pdf",
      pdfName: "Dashboard Analytics",
    },
    tasks: [
      "Dashboard créé",
      "Graphiques avancés",
      "Export données",
      "Tests utilisateurs",
    ],
    team: [
      { name: "Sophie Martin", role: "Data Visualization Expert", avatar: "👩‍💻" },
      { name: "Lucas Bernard", role: "Frontend Developer", avatar: "👨‍💻" },
      { name: "Julie Rousseau", role: "Data Analyst", avatar: "👩‍💻" },
      { name: "Pierre Dubois", role: "UX Designer", avatar: "👨‍🎨" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 12,
    name: "Projet Mu",
    progress: 41,
    description:
      "Développement d'une API RESTful avec documentation complète",
    longDescription:
      "Ce projet se concentre sur le développement d'une API RESTful robuste avec une documentation complète et des tests automatisés pour assurer la qualité et la maintenabilité.",
    details: {
      startDate: "25 Mars 2024",
      endDate: "15 Août 2024",
      team: "3 développeurs",
    },
    deadline: {
      kickOff: "30 Mars 2024",
      followUp: "25 Avril 2024",
      keynote: "10 Août 2024",
      daysRemaining: 130,
    },
    documentation: {
      pdfUrl: "/docs/projet-mu.pdf",
      pdfName: "API Documentation",
    },
    tasks: [
      "Architecture API",
      "Endpoints créés",
      "Documentation Swagger",
      "Tests d'intégration",
    ],
    team: [
      { name: "Camille Rousseau", role: "API Developer", avatar: "👩‍💻" },
      { name: "Antoine Lefevre", role: "Backend Developer", avatar: "👨‍💻" },
      { name: "Sarah Dubois", role: "Technical Writer", avatar: "👩‍💻" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 13,
    name: "Projet Nu",
    progress: 58,
    description: "Système de gestion de contenu avec éditeur WYSIWYG",
    longDescription:
      "Ce projet vise à créer un système de gestion de contenu moderne avec un éditeur WYSIWYG intuitif pour permettre aux utilisateurs de créer et gérer facilement leur contenu.",
    details: {
      startDate: "5 Avril 2024",
      endDate: "25 Septembre 2024",
      team: "4 développeurs",
    },
    deadline: {
      kickOff: "10 Avril 2024",
      followUp: "5 Mai 2024",
      keynote: "20 Septembre 2024",
      daysRemaining: 150,
    },
    documentation: {
      pdfUrl: "/docs/projet-nu.pdf",
      pdfName: "CMS WYSIWYG",
    },
    tasks: [
      "Éditeur créé",
      "Gestion médias",
      "Workflow publication",
      "Tests utilisateurs",
    ],
    team: [
      { name: "Emma Roux", role: "Frontend Developer", avatar: "👩‍💻" },
      { name: "Maxime Bernard", role: "Backend Developer", avatar: "👨‍💻" },
      { name: "Laura Moreau", role: "UI/UX Designer", avatar: "👩‍🎨" },
      { name: "Nicolas Simon", role: "Content Strategist", avatar: "👨‍💻" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 14,
    name: "Projet Xi",
    progress: 29,
    description: "Plateforme de collaboration en temps réel",
    longDescription:
      "Ce projet vise à créer une plateforme de collaboration en temps réel permettant aux équipes de travailler ensemble efficacement avec des outils de communication et de partage intégrés.",
    details: {
      startDate: "10 Avril 2024",
      endDate: "30 Novembre 2024",
      team: "5 développeurs",
    },
    deadline: {
      kickOff: "15 Avril 2024",
      followUp: "10 Mai 2024",
      keynote: "25 Novembre 2024",
      daysRemaining: 210,
    },
    documentation: {
      pdfUrl: "/docs/projet-xi.pdf",
      pdfName: "Collaboration Platform",
    },
    tasks: [
      "WebSocket implémenté",
      "Chat en temps réel",
      "Partage documents",
      "Tests de charge",
    ],
    team: [
      { name: "Sophie Martin", role: "Real-time Engineer", avatar: "👩‍💻" },
      { name: "Lucas Bernard", role: "Frontend Developer", avatar: "👨‍💻" },
      { name: "Julie Rousseau", role: "Backend Developer", avatar: "👩‍💻" },
      { name: "Pierre Dubois", role: "DevOps Engineer", avatar: "👨‍💻" },
      { name: "Camille Leroy", role: "QA Engineer", avatar: "👩‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 15,
    name: "Projet Omicron",
    progress: 81,
    description: "Application de gestion de projet avec Gantt",
    longDescription:
      "Ce projet vise à créer une application complète de gestion de projet avec des diagrammes de Gantt interactifs pour visualiser et planifier les projets efficacement.",
    details: {
      startDate: "15 Avril 2024",
      endDate: "20 Août 2024",
      team: "4 développeurs",
    },
    deadline: {
      kickOff: "20 Avril 2024",
      followUp: "15 Mai 2024",
      keynote: "15 Août 2024",
      daysRemaining: 100,
    },
    documentation: {
      pdfUrl: "/docs/projet-omicron.pdf",
      pdfName: "Gantt Charts",
    },
    tasks: [
      "Diagramme Gantt",
      "Gestion tâches",
      "Notifications",
      "Tests fonctionnels",
    ],
    team: [
      { name: "Antoine Lefevre", role: "Project Manager", avatar: "👨‍💻" },
      { name: "Sarah Dubois", role: "Frontend Developer", avatar: "👩‍💻" },
      { name: "Maxime Bernard", role: "Backend Developer", avatar: "👨‍💻" },
      { name: "Laura Moreau", role: "UI/UX Designer", avatar: "👩‍🎨" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
  {
    id: 16,
    name: "Projet Pi",
    progress: 66,
    description: "Système de réservation et de gestion d'agenda",
    longDescription:
      "Ce projet vise à créer un système de réservation et de gestion d'agenda intelligent permettant aux utilisateurs de planifier et gérer leurs rendez-vous efficacement.",
    details: {
      startDate: "20 Avril 2024",
      endDate: "15 Septembre 2024",
      team: "3 développeurs",
    },
    deadline: {
      kickOff: "25 Avril 2024",
      followUp: "20 Mai 2024",
      keynote: "10 Septembre 2024",
      daysRemaining: 125,
    },
    documentation: {
      pdfUrl: "/docs/projet-pi.pdf",
      pdfName: "Booking System",
    },
    tasks: [
      "Calendrier créé",
      "Système réservation",
      "Notifications email",
      "Tests d'acceptation",
    ],
    team: [
      { name: "Emma Roux", role: "Full-stack Developer", avatar: "👩‍💻" },
      { name: "Nicolas Simon", role: "Backend Developer", avatar: "👨‍💻" },
      { name: "Claire Dubois", role: "QA Engineer", avatar: "👩‍🔬" },
    ],
    trophies: [
      { name: "deploy-poll", obtained: true, description: "Déployer le service poll avec succès." },
      { name: "deploy-result", obtained: false, description: "Déployer le service result avec succès." },
      { name: "deploy-worker", obtained: true, description: "Déployer le worker avec succès." },
      { name: "deploy-postgres", obtained: true, description: "Déployer la base de données Postgres." },
      { name: "deploy-redis", obtained: true, description: "Déployer le cache Redis." },
      { name: "deploy-traefik", obtained: false, description: "Déployer le reverse proxy Traefik." },
      { name: "configmap-postgres", obtained: true, description: "Configurer le ConfigMap pour Postgres." },
      { name: "configmap-redis", obtained: true, description: "Configurer le ConfigMap pour Redis." },
      { name: "secrets", obtained: true, description: "Configurer les secrets d'environnement." },
      { name: "env-poll", obtained: true, description: "Configurer les variables d'environnement pour poll." },
      { name: "env-result", obtained: true, description: "Configurer les variables d'environnement pour result." },
      { name: "env-worker", obtained: true, description: "Configurer les variables d'environnement pour worker." },
      { name: "env-postgres", obtained: true, description: "Configurer les variables d'environnement pour Postgres." },
      { name: "vol-postgres", obtained: true, description: "Configurer le volume pour Postgres." },
      { name: "vol-deploy", obtained: true, description: "Configurer le volume pour le déploiement." },
      { name: "service-postgres", obtained: true, description: "Déployer le service Postgres." },
      { name: "service-redis", obtained: true, description: "Déployer le service Redis." },
      { name: "service-poll", obtained: true, description: "Déployer le service poll." },
      { name: "service-traefik", obtained: true, description: "Déployer le service Traefik." },
      { name: "ingress-poll", obtained: true, description: "Configurer l'ingress pour poll." },
      { name: "ingress-result", obtained: true, description: "Configurer l'ingress pour result." },
      { name: "affinity-poll", obtained: true, description: "Configurer l'affinité pour poll." },
      { name: "resources-poll", obtained: true, description: "Configurer les ressources pour poll." },
      { name: "affinity-result", obtained: true, description: "Configurer l'affinité pour result." },
      { name: "resources-result", obtained: true, description: "Configurer les ressources pour result." },
      { name: "affinity-traefik", obtained: false, description: "Configurer l'affinité pour Traefik." },
      { name: "daemonset-cadvisor", obtained: false, description: "Déployer le DaemonSet cadvisor." },
      { name: "daemonset-volume", obtained: false, description: "Configurer le volume pour le DaemonSet." },
      { name: "perfection", obtained: false, description: "Obtenir tous les autres trophées !" },
    ],
    hotTopics: [
      { title: "Déploiement CI/CD", description: "Automatisation du pipeline de déploiement continu." },
      { title: "Sécurité API", description: "Gestion des accès et sécurisation des endpoints." }
    ],
    skills: ["React", "Node.js", "Docker", "CI/CD", "API REST"],
  },
];

// Fonction pour récupérer un projet par son ID
export const getProjectById = (id: number) => {
  return projects.find(project => project.id === id);
};

// Fonction pour récupérer tous les projets
export const getAllProjects = () => {
  return projects;
};
